[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.18"

[features]
resolution = true
skip-lint = false

[programs.devnet]
ico_launchpad = "373N2AQZikw4v5w1dq2TrWdQDRh87jhj93zBdGH25CVX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true
